default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>
  timeout: 5000

development:
  <<: *default
  database: any_rails_demo_dev

test:
  <<: *default
  database: any_rails_demo_test

production:
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>
